apiVersion: v2
description: A helper Chart which creates a job to verify if the deployments of an
  operator are running. To do so it creates a service account with a role to read
  the status of the Deployments
home: https://github.com/tjungbauer/helm-charts/tree/main/charts/helper-status-checker
icon: https://github.com/tjungbauer/helm-charts/raw/gh-pages/images/helping.png
maintainers:
- email: tjungbau@redhat.com
  name: tjungbauer
name: helper-status-checker
sources:
- https://github.com/tjungbauer/helm-charts
version: 2.0.2
