{{- with .Values }}
{{ if eq ( .enabled | toString) "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helper.serviceAccountName" $ }}
  namespace: {{ .namespace.name | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: {{ .syncwave | default 1 | quote }}
{{- end }}
{{- end }}