{{- with .Values.loggingConfig }}
{{ if eq ( .enabled | toString) "true" }}
---
apiVersion: "logging.openshift.io/v1"
kind: "ClusterLogging"
metadata:
  name: "instance" 
  namespace: "openshift-logging"
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    {{- if eq ( $.Values.vector | toString) "true" }}
    logging.openshift.io/preview-vector-collector: enabled
    {{- end }}
spec:
  managementState: "Managed"
  {{- if eq ( $.Values.elasticsearch | toString) "true" }}
  logStore:
    type: "elasticsearch"
    elasticsearch:
      nodeCount: {{ .es.nodes }}
      storage:
        storageClassName: {{ .es.storageclass | quote }}
        size: {{ .es.storagesize }}
      resources: 
          limits:
            memory: {{ .es.limits.mem | quote }}
          requests:
            memory: {{ .es.requests.mem | quote }}
      proxy:
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
      redundancyPolicy: {{ .es.redundancyPolicy | quote }}
      retentionPolicy: 
        application:
          maxAge: {{ .retentionPolicy.application | default "1d" }}
        infra:
          maxAge: {{ .retentionPolicy.infra | default "1d" }}
        audit:
          maxAge: {{ .retentionPolicy.audit | default "1d" }}
  visualization:
    type: "kibana"
    kibana:
      replicas: 1
  collection:
    logs:
      type: "fluentd"
      fluentd: {}
  {{- end }}
  {{- if eq ( $.Values.lokistack | toString) "true" }}
  logStore:
    type: lokistack
    lokistack:
      name: logging-loki
  collection:
    type: vector
    logs:
      type: vector
  {{- end }}
{{- end }}
{{- end }}
